title: My GitHub Pages Site
description: Welcome to my awesome site!
theme: minima
# Set your baseurl if your site is in a subdirectory (uncomment and edit below)
# baseurl: "/your-repo-name"
# Set the URL of your site (uncomment and edit below)
# url: "https://yourusername.github.io"
